"""Coating catalogue: in-memory model of bundled + user coating presets.

Read-only after load. The designer's coating "Preset" picker reads from
:class:`CoatingCatalogue`; applying a preset **copies** its ``payload`` (a
JSON coating-modifier dict, in the same shape the ``.lens`` writer emits and
the C++ parser reads) onto the target surface. There is no live link — a
``.lens`` file has no coating-catalogue section by design (coatings are
inline per surface), so the catalogue is purely an authoring convenience.
See [`COATING_CATALOGUE.md`](../COATING_CATALOGUE.md).

Mirrors :mod:`ghostlight_designer.material_catalogue`: bundled JSON lives under
:mod:`ghostlight_designer.resources.coatings` (generated by
``tools/build_coating_catalogue.py``); a user file merges on top, user wins.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path
from typing import Iterable, Iterator, List, Optional, Tuple

logger = logging.getLogger(__name__)


CATALOGUE_FORMAT = "ghostlight-coating-catalogue"
CATALOGUE_MAJOR_VERSION = 1


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CatalogueCoating:
    """One picker-facing coating preset entry."""

    key: str                         # stable catalogue key (unique)
    display_name: str
    source_vendor: str               # provenance label, e.g. "Built-in" / "User"
    tags: Tuple[str, ...]
    description: str

    # The coating-modifier dict copied onto a surface when the preset is
    # applied. Same shape as one entry of a surface's ``modifiers`` array
    # (e.g. {"type":"coating","model":"artist","tint":[...],"strength":...}
    # or {"type":"coating","layers":[...]}). This is the ONLY field that
    # affects a lens.
    payload: dict = field(default_factory=dict)

    def payload_json(self) -> str:
        """The payload as a compact JSON string (what the picker returns)."""
        return json.dumps(self.payload)


# ---------------------------------------------------------------------------
# Envelope → CatalogueCoating parsing
# ---------------------------------------------------------------------------

def _iter_envelope(envelope: dict) -> Iterator[CatalogueCoating]:
    """Yield entries from a ``ghostlight-coating-catalogue`` envelope dict.

    Tolerant: an entry missing ``key`` or ``payload`` is skipped with a log
    line rather than aborting the whole file, so one malformed preset can't
    deny the user the rest of the catalogue.
    """
    if not isinstance(envelope, dict):
        return
    vendor = str(envelope.get("source", "Built-in"))
    for entry in envelope.get("coatings", []):
        if not isinstance(entry, dict):
            continue
        key = entry.get("key")
        payload = entry.get("payload")
        if not key or not isinstance(payload, dict):
            logger.warning("Skipping coating preset with no key/payload: %r", entry)
            continue
        yield CatalogueCoating(
            key=str(key),
            display_name=str(entry.get("display_name", key)),
            source_vendor=str(entry.get("source_vendor", vendor)),
            tags=tuple(str(t) for t in entry.get("tags", ())),
            description=str(entry.get("description", "")),
            payload=payload,
        )


# ---------------------------------------------------------------------------
# Catalogue container
# ---------------------------------------------------------------------------

class CoatingCatalogue:
    """Flat, read-only collection of :class:`CatalogueCoating` presets.

    Indexed by catalogue key; insertion order preserved. On key collision
    the later insertion wins (bundled first, user last, user wins).
    """

    def __init__(self, coatings: Iterable[CatalogueCoating] = ()) -> None:
        self._by_key: dict[str, CatalogueCoating] = {}
        for c in coatings:
            self._add(c)

    def _add(self, c: CatalogueCoating) -> None:
        self._by_key[c.key] = c

    # -- Read API --

    def all(self) -> List[CatalogueCoating]:
        return list(self._by_key.values())

    def by_key(self, key: str) -> Optional[CatalogueCoating]:
        return self._by_key.get(key)

    def search(
        self,
        *,
        tag: Optional[str] = None,
        vendor: Optional[str] = None,
        query: Optional[str] = None,
    ) -> List[CatalogueCoating]:
        """Filter by tag / vendor / free-text query (all optional, ANDed)."""
        tag_lc = tag.lower() if tag else None
        vendor_lc = vendor.lower() if vendor else None
        query_lc = query.lower() if query else None
        out: list[CatalogueCoating] = []
        for c in self._by_key.values():
            if vendor_lc is not None and c.source_vendor.lower() != vendor_lc:
                continue
            if tag_lc is not None and tag_lc not in (t.lower() for t in c.tags):
                continue
            if query_lc is not None:
                hay = " ".join((
                    c.key, c.display_name, c.description, " ".join(c.tags),
                )).lower()
                if query_lc not in hay:
                    continue
            out.append(c)
        return out

    def __len__(self) -> int:
        return len(self._by_key)

    def __iter__(self) -> Iterator[CatalogueCoating]:
        return iter(self._by_key.values())

    def __contains__(self, key: object) -> bool:
        return key in self._by_key

    # -- Loaders --

    @classmethod
    def load_bundled(cls) -> "CoatingCatalogue":
        """Load every ``*.json`` under :mod:`ghostlight_designer.resources.coatings`."""
        cat = cls()
        try:
            pkg_files = resources.files("ghostlight_designer.resources.coatings")
        except (ModuleNotFoundError, FileNotFoundError):
            logger.warning("No bundled coating catalogue found")
            return cat
        for entry in sorted(pkg_files.iterdir(), key=lambda e: e.name):
            if not entry.name.endswith(".json"):
                continue
            try:
                with entry.open("r", encoding="utf-8") as fh:
                    envelope = json.load(fh)
                for c in _iter_envelope(envelope):
                    cat._add(c)
            except Exception:
                logger.exception("Failed to load bundled coating catalogue %s",
                                 entry.name)
        return cat

    @classmethod
    def load_from_files(cls, paths: Iterable[Path]) -> "CoatingCatalogue":
        """Test helper: build a catalogue from explicit JSON file paths."""
        cat = cls()
        for path in paths:
            with open(path, "r", encoding="utf-8") as fh:
                envelope = json.load(fh)
            for c in _iter_envelope(envelope):
                cat._add(c)
        return cat

    @classmethod
    def load_with_user(cls, user_path: Optional[Path] = None) -> "CoatingCatalogue":
        """Load bundled catalogue and (if present) merge a user catalogue."""
        cat = cls.load_bundled()
        if user_path is not None and user_path.is_file():
            try:
                with open(user_path, "r", encoding="utf-8") as fh:
                    envelope = json.load(fh)
                for c in _iter_envelope(envelope):
                    cat._add(c)
            except Exception:
                logger.exception("Failed to load user coating catalogue %s",
                                 user_path)
        return cat


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

_singleton: Optional[CoatingCatalogue] = None


def get_coating_catalogue() -> CoatingCatalogue:
    """Lazy bundled-only catalogue accessor (mirrors material get_catalogue)."""
    global _singleton
    if _singleton is None:
        _singleton = CoatingCatalogue.load_bundled()
    return _singleton


def reset_singleton() -> None:
    """Drop the cached singleton (tests + user-catalogue reloads)."""
    global _singleton
    _singleton = None
