"""Material catalogue: in-memory model of bundled vendor glasses + user glasses.

Read-only after load. The designer's glass picker reads from
:class:`MaterialCatalogue`; the active runtime dispersion model is the
``dispersion`` field, which is the **only** thing that propagates into a
``.lens`` file's ``glass_catalogue`` — see
[`resources/materials/README.md`](resources/materials/README.md).

Bundled JSON lives under :mod:`ghostlight_designer.resources.materials`
(one file per vendor, generated by
``tools/build_material_catalogue.py``). The user-catalogue file lives
under :class:`QStandardPaths.AppDataLocation` and is loaded alongside the
bundled files on demand.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Iterable, Iterator, List, Optional, Tuple

logger = logging.getLogger(__name__)


CATALOGUE_FORMAT = "ghostlight-material-catalogue"
CATALOGUE_MAJOR_VERSION = 1


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CatalogueMaterial:
    """One picker-facing material entry."""

    key: str                                    # written into .lens material_glasses
    display_name: str
    catalogue_ref: str                          # vendor provenance (may be "")
    source_vendor: str                          # "Schott" / "Ohara" / "Hoya" /
                                                #   "CDGM" / "Hikari" / "LZOS" / "User"
    tags: Tuple[str, ...]

    # Active runtime model — the ONLY thing copied into .lens files.
    dispersion: dict

    # Designer-side metadata for picker chrome (tooltips, filtering).
    nd: Optional[float]
    vd: Optional[float]
    wavelength_range_nm: Optional[Tuple[float, float]]
    glass_code: str
    glass_status: str
    density_g_cm3: Optional[float]
    description: str
    comments: str
    references: str
    source_file: str

    # Full original source data kept for picker n(λ) plots and possible
    # tracer extensions. NEVER passed into any .lens writer path.
    raw_source: Optional[dict]

    def lens_catalogue_entry(self) -> dict:
        """The exact dict to assign to ``system._raw_glass_catalogue[self.key]``.

        Centralises the rule that only ``dispersion`` + display name + ref
        leak into ``.lens`` files; the test suite asserts ``raw_source``
        never appears in this output.

        Returns a deep copy so callers that subsequently mutate the
        returned dict (or its nested ``B`` / ``C`` lists) can't corrupt
        the catalogue's authoritative entry.
        """
        from copy import deepcopy
        return {
            "name":          self.display_name,
            "catalogue_ref": self.catalogue_ref,
            "dispersion":    deepcopy(self.dispersion),
        }


# ---------------------------------------------------------------------------
# Envelope → CatalogueMaterial parsing
# ---------------------------------------------------------------------------

def _wavelength_range(ui: dict) -> Optional[Tuple[float, float]]:
    wr = ui.get("wavelength_range_nm")
    if isinstance(wr, (list, tuple)) and len(wr) == 2:
        return (float(wr[0]), float(wr[1]))
    return None


def _opt_float(value) -> Optional[float]:
    return float(value) if value is not None else None


def _material_from_json(key: str, vendor: str, raw: dict) -> CatalogueMaterial:
    ui = raw.get("ui") or {}
    tags = raw.get("tags") or []
    return CatalogueMaterial(
        key=key,
        display_name=str(raw.get("display_name", "")),
        catalogue_ref=str(raw.get("catalogue_ref", "")),
        source_vendor=vendor,
        tags=tuple(str(t) for t in tags),
        dispersion=dict(raw.get("dispersion") or {}),
        nd=_opt_float(ui.get("nd")),
        vd=_opt_float(ui.get("vd")),
        wavelength_range_nm=_wavelength_range(ui),
        glass_code=str(ui.get("glass_code", "")),
        glass_status=str(ui.get("glass_status", "")),
        density_g_cm3=_opt_float(ui.get("density_g_cm3")),
        description=str(ui.get("description", "")),
        comments=str(ui.get("comments", "")),
        references=str(ui.get("references", "")),
        source_file=str(ui.get("source_file", "")),
        raw_source=dict(raw["raw_source"]) if raw.get("raw_source") is not None else None,
    )


def _iter_envelope(envelope: dict) -> Iterator[CatalogueMaterial]:
    """Validate the envelope and yield each material as a CatalogueMaterial.

    Raises ``ValueError`` on unrecognised format / major version. Unknown
    fields inside materials are tolerated and silently ignored — the
    schema is intentionally additive across minor versions.
    """
    fmt = envelope.get("format")
    if fmt != CATALOGUE_FORMAT:
        raise ValueError(f"unrecognised catalogue format: {fmt!r}")
    version = envelope.get("version") or {}
    major = version.get("major")
    if major != CATALOGUE_MAJOR_VERSION:
        raise ValueError(
            f"unsupported catalogue major version {major} "
            f"(expected {CATALOGUE_MAJOR_VERSION})"
        )
    source = envelope.get("source") or {}
    vendor = str(source.get("vendor", ""))
    for key, raw in (envelope.get("materials") or {}).items():
        if not isinstance(raw, dict):
            continue
        yield _material_from_json(str(key), vendor, raw)


# ---------------------------------------------------------------------------
# Catalogue container
# ---------------------------------------------------------------------------

class MaterialCatalogue:
    """Flat, read-only collection of :class:`CatalogueMaterial` entries.

    Indices kept:
      * by catalogue key (the string that goes into ``.lens`` files)
      * by ``catalogue_ref`` (vendor provenance, e.g. ``Schott:N-BK7``)

    Insertion order is preserved by both indices (Python ``dict`` semantics).
    On key collision the **later** insertion wins — the design contract is
    "bundled catalogue first, user catalogue last, user wins."
    """

    def __init__(self, materials: Iterable[CatalogueMaterial] = ()) -> None:
        self._by_key: dict[str, CatalogueMaterial] = {}
        self._by_ref: dict[str, CatalogueMaterial] = {}
        for m in materials:
            self._add(m)

    def _add(self, m: CatalogueMaterial) -> None:
        self._by_key[m.key] = m
        if m.catalogue_ref:
            self._by_ref[m.catalogue_ref] = m

    # -- Read API --

    def all(self) -> List[CatalogueMaterial]:
        return list(self._by_key.values())

    def by_key(self, key: str) -> Optional[CatalogueMaterial]:
        return self._by_key.get(key)

    def by_ref(self, catalogue_ref: str) -> Optional[CatalogueMaterial]:
        return self._by_ref.get(catalogue_ref)

    def search(
        self,
        *,
        tag: Optional[str] = None,
        vendor: Optional[str] = None,
        query: Optional[str] = None,
    ) -> List[CatalogueMaterial]:
        """Filter by tag / vendor / free-text query (all optional, ANDed)."""
        tag_lc = tag.lower() if tag else None
        vendor_lc = vendor.lower() if vendor else None
        query_lc = query.lower() if query else None
        out: list[CatalogueMaterial] = []
        for m in self._by_key.values():
            if vendor_lc is not None and m.source_vendor.lower() != vendor_lc:
                continue
            if tag_lc is not None and tag_lc not in (t.lower() for t in m.tags):
                continue
            if query_lc is not None:
                hay = " ".join((
                    m.key, m.display_name, m.catalogue_ref,
                    m.description, m.comments, " ".join(m.tags),
                )).lower()
                if query_lc not in hay:
                    continue
            out.append(m)
        return out

    def __len__(self) -> int:
        return len(self._by_key)

    def __iter__(self) -> Iterator[CatalogueMaterial]:
        return iter(self._by_key.values())

    def __contains__(self, key: object) -> bool:
        return key in self._by_key

    # -- Loaders --

    @classmethod
    def load_bundled(cls) -> "MaterialCatalogue":
        """Load every ``<vendor>.json`` under :mod:`ghostlight_designer.resources.materials`.

        Files are loaded in alphabetical order; within each file the
        envelope's material insertion order is preserved. A malformed
        file logs an exception but doesn't abort the whole load — better
        to ship one vendor partially than to leave the user with no
        catalogue at all.
        """
        cat = cls()
        try:
            pkg_files = resources.files("ghostlight_designer.resources.materials")
        except (ModuleNotFoundError, FileNotFoundError):
            logger.warning("No bundled material catalogue found")
            return cat
        for entry in sorted(pkg_files.iterdir(), key=lambda e: e.name):
            if not entry.name.endswith(".json"):
                continue
            try:
                with entry.open("r", encoding="utf-8") as fh:
                    envelope = json.load(fh)
                for m in _iter_envelope(envelope):
                    cat._add(m)
            except Exception:
                logger.exception("Failed to load bundled catalogue %s", entry.name)
        return cat

    @classmethod
    def load_from_files(cls, paths: Iterable[Path]) -> "MaterialCatalogue":
        """Test helper: build a catalogue from explicit JSON file paths."""
        cat = cls()
        for path in paths:
            with open(path, "r", encoding="utf-8") as fh:
                envelope = json.load(fh)
            for m in _iter_envelope(envelope):
                cat._add(m)
        return cat

    @classmethod
    def load_with_user(
        cls,
        user_path: Optional[Path] = None,
    ) -> "MaterialCatalogue":
        """Load bundled catalogue and (if present) merge a user catalogue.

        ``user_path`` should point at the writable user-catalogue file
        (typically :func:`user_catalogue_path`). Missing files are silently
        skipped; load failures log and continue with bundled-only data.
        """
        cat = cls.load_bundled()
        if user_path is not None and user_path.is_file():
            try:
                with open(user_path, "r", encoding="utf-8") as fh:
                    envelope = json.load(fh)
                for m in _iter_envelope(envelope):
                    cat._add(m)
            except Exception:
                logger.exception("Failed to load user catalogue %s", user_path)
        return cat


# ---------------------------------------------------------------------------
# Singleton + path helpers
# ---------------------------------------------------------------------------

_singleton: Optional[MaterialCatalogue] = None


def get_catalogue() -> MaterialCatalogue:
    """Lazy bundled-only catalogue accessor.

    Used by code paths that don't have a chance to receive an injected
    catalogue — notably the headless element-creation helpers in
    :mod:`ghostlight_designer.optical_editor.element_actions`. The
    application bootstrap loads the catalogue once during start-up
    (with the user overlay) and injects it into the main window; that
    instance should always be used for picker UI rather than this
    singleton.
    """
    global _singleton
    if _singleton is None:
        _singleton = MaterialCatalogue.load_bundled()
    return _singleton


def reset_singleton() -> None:
    """Test helper: drop the cached bundled-catalogue singleton."""
    global _singleton
    _singleton = None


def user_catalogue_path() -> Path:
    """Writable user-catalogue location under :class:`QStandardPaths.AppDataLocation`.

    Returns the expected ``<AppData>/materials/user.json`` path even if
    the file or its parent directory does not yet exist. Imported here
    rather than at module top so headless / Qt-less code can import the
    rest of this module without pulling in PySide6.
    """
    from PySide6.QtCore import QStandardPaths

    base = QStandardPaths.writableLocation(QStandardPaths.AppDataLocation)
    return Path(base) / "materials" / "user.json"
